import { Trips } from '@/components/Trips';

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div>
      <Trips />
    </div>
  );
}
